# Filter the list of presented browser by the fact if a browser is already opened
# More information: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#useonlyrunningbrowsers
useOnlyRunningBrowsers = false

# Removing some tracking attributes from URLs
# More information: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#striptrackingattributes
stripTrackingAttributes = true

# Resolves the final URL that is hidden under shorten URL
# More information and how to combine with other features: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#expandShortenURLs
expandShortenURLs = true

# Number of seconds to make a browser the default one temporary
# Mope information: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#pinningseconds
pinningSeconds = 30

# Level of verbosity for .eligere.log for troubleshooting
# More information: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#loglevel
logLevel = "warning"

[[browsers]]
# Name of a browser from "/Applications" folder. Required property.
# If set incorrectly - browser configuration will be ignored.
# More information: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#name
name = "Safari"

# Keyboard shortcut to open this browser.
# More information: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#shortcut
shortcut = "s"

# Eligere can map all links for "apps" applications to this browser configuration.
# Mor information: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#apps---optional
apps = ["Messages"]

# Eligere can map specific links to this browser configuration.
# More information: https://github.com/RomanVolkov/eligere_app/tree/main/docs/config.md#domains
domains = ["apple.com"]

